---
db:
    url: "http://arangodb:8529"
    name: "snakepit"
    root:
        name: "root"
        password: "qwertyuiop"
    user:
        name: "snakepit"
        password: "qwertyuiop"
        
app:
    port: 3000
    timeout: 5s
    policyName: "snakepit"
        
services:
    authServer:
        url: "http://auth-server:3000"